### ISSUE TITLE
SQL injection vulnerability 

### ISSUE THREAD

**Issue by baditaflorin** [sudiptog81/sql2geojson#6]
You can test using this query 
https://sql2geojson.herokuapp.com/postgres/api/test?fields=id&filter=2or%201=1

**How do you expect:**
To filter and see just id=2 

**What do you see in reality?**
The query return everything from the database.

https://www.w3schools.com/sql/sql_injection.asp
The fix would be to use prepared statements before sending to the database.

**Comment by sudiptog81** [comment]
Seems to affect the Postgres API more than the MySQL API. Added some more sanity checks. 

Fixed in #7. Re-open if encountered again.
